# Generated by Django 4.2.17 on 2025-02-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoapDispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soap_level', models.FloatField(help_text='Soap level in percentage')),
                ('last_refill', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
