# Generated by Django 5.1.4 on 2025-02-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispenser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapdispenser',
            name='last_refill',
            field=models.CharField(help_text='Formated: YYYY-MM-DD HH:MM:SS', max_length=19),
        ),
        migrations.AlterField(
            model_name='soapdispenser',
            name='soap_level',
            field=models.FloatField(help_text='Soap Level in percentage'),
        ),
    ]
