# Generated by Django 5.1.4 on 2025-01-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_url',
            new_name='image_blob',
        ),
    ]
