# Generated by Django 5.1.4 on 2025-01-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_image_url_car_image_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='details',
        ),
        migrations.AlterField(
            model_name='car',
            name='image_blob',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
