# Generated by Django 5.1.4 on 2025-01-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_details_alter_car_image_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
