# Generated by Django 5.1.4 on 2025-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_image_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_blob',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
